version: "3.9"
services:
  web:
    build: ./apps/web
    ports: ["3000:3000"]
    env_file: .env
    depends_on: [api, db, redis]
  api:
    build: ./apps/api
    ports: ["8000:8000"]
    env_file: .env
    depends_on: [db, redis, minio]
  worker:
    build: ./apps/api
    command: ["python", "-m", "worker.main"]
    env_file: .env
    depends_on: [api, db, redis, minio]
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: claimscope
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes: ["miniodata:/data"]
volumes:
  pgdata:
  miniodata:
